Mark BROKEN: missing dependency
===>  Staging for R-cran-car-2.0.25
===>   Generating temporary packing list
ERROR: dependencies 'pbkrtest', 'quantreg' are not available for package 'car'

Reported by:	pkg-fallout