Add camlp4 dependency after r385012 uncovered by r385413
devel/ocaml-lwt (4 skipped) is still broken by another issue:

  File "src/top/toplevel.ml", line 60, characters 17-62:
  Error: This expression has type load:bool -> Path.t
         but an expression was expected of type 'a * 'b

PR:		199845
Reported by:	pkg-fallout
Approved by:	portmgr blanket