textproc/gnugrep: Add missing libiconv dependency
GNU Grep's automatically searches for and detects (via configure) the
presence of gettext and libiconv. If libiconv is already installed it
results in libiconv being detected without the dependency being
registered. If libiconv is ever removed, the following error is
observed:

  Error: Shared object "libiconv.so.2" not found, required by "grep"

This change adds explicit configure arguments to disable gettext and
libiconv detection when their respective OPTIONS are disabled.

Additionally it adds an ICONV option consistent with other
ports, and replaces global CPPFLAGS and LDFLAGS values
with GETTEXT and ICONV option-specific library and include configure
arguments for the respective search path prefixes.

Note: CPPFLAGS and LDFLAGS are still required for PCRE detection, as
the configure script does not provide equivalent -prefix=[PATH] options
for libpcre. These flags are now PCRE option conditional.

While I'm here:

- Sort USES and OPTIONS and improve readability by seperating those
  sections by whitespace.
- Add LICENSE_FILE

Tested on:	9.3, 10.1, i386, amd64, all PCRE, ICONV, NLS permutations
Approved:	portmgr (blanket, framework compliance)